Codeminer42/Punchclock

- config/initializers/active_admin.rb
- config/locales/en/active_admin.yml
- config/locales/pt-BR/active_admin.yml
- config/locales/pt-BR/pt-BR.yml
Added the translation string in the i18n resources and replaced the hardcoded label with a call to the rails I18N service.
Closes #3
> Use i18n in active_admin.rb

- app/controllers/application_controller.rb
- app/decorators/user_decorator.rb
- app/views/refills/_navigation.html.erb
- spec/controllers/application_controller_spec.rb
- spec/decorators/user_decorator_spec.rb
Added the current allocation below the name of the user in the navbar.
Closes #5
> Adds user's current allocation in navbar

- Gemfile
- Gemfile.lock
Removed rails_12factor from Gemfile and Gemfile.lock.
Closes #28
> remove 'rails_12factor' from Gemfile

- app/controllers/application_controller.rb
- config/locales/en/devise.yml
- config/locales/pt-BR/devise.yml
- Added the translation string in the i18n resources
- Replaced the hardcoded label with a call to the rails I18N service.
Closes #32
> Use i18n in application_controller

- app/javascript/packs/components/Form.js
- spec/features/dashboard_spec.rb
This PR addresses issue #9 
The value of the project selector is now being stored in a state in order to control the disabled state of the save button.
The dashboard tests have been updated to select a project before trying to save the form.
A new test has been created to validate if the button is really disabled when no project is selected.
> Disable save button when no project is selected

- app/controllers/punches_controller.rb
- app/views/punches/index.html.erb
Fixes #16 and #17
This PR merges the two parts of a Punch and displays as one. The punch table is now as shown below.
> Simplify punches table

- app/views/refills/_navigation.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/locales/pt-BR/views.yml
Currently, to access the administrative dashboard, the user must type "/admin" at the end of the URL. This PR fixes this by adding an "Administrative" link on the header of the page.
If the current user is an admin:
Otherwise:
Closes #25
> Add "Administrative" item to admin users on navbar

- spec/factories/punches.rb
- spec/features/punches_list_spec.rb
- spec/fixtures/attachment.txt
The attachment link rendering and its click action weren't being tested.
To test this:
1. Created a with_attachment trait in the punch factory.
2. Created attachment fixture.
3. Instantiated a punch with attachment before tests.
4. Tested if punch.attachment_url was rended on the page.
5. Tested if attachment content was shown after click.
> Create punch attachment tests

- app/queries/contributions_by_office_query.rb
- spec/queries/contributions_by_office_query_spec.rb
This test only broke during january, worked fine in other months.
When past month went over to another year, the query failed.
Changed per_month argument to receive a date, not a month.
Maybe this will break something, but all tests passed.
> Fix contribuitions by office by month test

- app/admin/contributions.rb
- app/models/contribution.rb
- spec/features/admin/contributions_spec.rb
- spec/models/contribution_spec.rb
- spec/queries/contributions_by_office_query_spec.rb
Closes #95 
I realized that contribution rows of inactive engineers were also displayed on the contributions index page, making them appear in the exports. 
I'm approaching this situation by filtering them out on the index page.
> Display only contributions of active engineers in contributions index

- spec/queries/contributions_by_user_query_spec.rb
* The old test fails when running in March, returning 6 contributions instead of the expected 3
* Changes descriptions to third-person singular
* Moves subject to the first position after `context` blocks
> Improves tests for ContributionsByUserQuery

- app/admin/contributions.rb
- app/queries/repositories_ordered_by_contributions_query.rb
- spec/queries/repositories_ordered_by_contributions_query_spec.rb
Resolve: [#114 ](https://github.com/Codeminer42/Punchclock/issues/114)
> Update repository select to show repositories ordered by total of contributions

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/punches_controller.rb
- app/serializers/project_serializer.rb
- app/serializers/punch_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/punches_controller_spec.rb
- spec/support/controller_helpers.rb
Issue: #104 
This PR adds an endpoint to list all punches registered to the authenticated user.
This is how the response is working:
```json
[
{
"created_at": "2022-04-26T09:53:51.248-03:00",
"from": "2021-10-26T08:00:00.000-03:00",
"to": "2021-10-26T12:00:00.000-03:00",
"delta_as_hour": "04:00",
"extra_hour": false,
"project": {
"name": "Rito Gomes"
}
},
{
"created_at": "2022-04-26T09:53:51.252-03:00",
"from": "2021-10-26T13:00:00.000-03:00",
"to": "2021-10-26T16:00:00.000-03:00",
"delta_as_hour": "03:00",
"extra_hour": false,
"project": {
"name": "Rito Gomes"
}
}
```
> Create all punches endpoint

- Gemfile.lock
- app/controllers/api/v1/punches_controller.rb
- config/routes.rb
- spec/controllers/api/v1/punches_controller_spec.rb
- spec/support/controller_helpers.rb
Issue: #105 
This PR adds an endpoint to list all punches registered to the authenticated user.
This is how the response is working:
```json
{
"created_at": "2022-04-26T09:53:22.722-03:00",
"from": "2021-10-26T13:00:00.000-03:00",
"to": "2021-10-26T16:00:00.000-03:00",
"delta_as_hour": "03:00",
"extra_hour": false,
"project": {
"name": "Punchclock"
}
}
```
> Show one Punch endpoint to authenticated user

- app/admin/allocations.rb
- app/models/allocation.rb
- config/locales/pt-BR/active_admin.yml
- spec/features/admin/allocations_spec.rb
- spec/models/allocation_spec.rb
> Update allocations page scopes

- app/admin/allocations.rb
- app/admin/user.rb
- app/models/allocation.rb
- config/locales/en/models.yml
- config/locales/pt-BR/models.yml
- db/migrate/20220817133652_add_ongoing_to_allocation.rb
- db/schema.rb
- lib/tasks/allocations.rake
- spec/factories/allocations.rb
- spec/features/admin/allocations_spec.rb
- spec/models/allocation_spec.rb
#163
* Add `ongoing` property to Allocation model
* Update `allocations` active admin pages to present/manipulate ongoing info
* Update `user` active admin page to present ongoing info
* Create task to set current users allocation ongoing property to true
* image 1
* image 2
* image 3
* image 4
* image 5
> Add ongoing property to Allocation model

- db/migrate/20220819180011_chage_allocation_ongoing_default.rb
- db/schema.rb
As mentioned in #163, the default value was temporarily defined as `false` to keep compatibility with the existing allocation data. So this PR will change the default to `true`.
> Changes allocation ongoing default form false to true

- app/admin/allocation_chart.rb
- app/assets/stylesheets/active_admin.scss
- app/queries/allocations_and_unalocated_users_query.rb
- spec/features/admin/allocation_chart_spec.rb
- spec/queries/allocations_and_unalocated_users_query_spec.rb
Now in allocation chart page, the column `Alocado até` shows expired allocation dates.
> Update allocation chart highlight considering allocation `ongoing` property

- spec/features/dashboard_spec.rb
This PR fixes a wrong test case of `spec/features/dashboard_spec.rb`
Problem: `spec/features/dashboard_spec.rb:78` let the user who doesn't have overtime allowed insert punches on holiday AND on holidays, the test would fail.
> Fix dashboard_spec test setup

- app/mailers/vacation_mailer.rb
- spec/mailers/vacation_mailer_spec.rb
Closes:  #305 
Now HR e-mail is copied into CC (Carbon Copy) field for every vacation e-mail (vacation request, vacation approved, vacation denied)
> Feature: Copy HR into vacation's e-mails

- app/controllers/vacations_controller.rb
- app/mailers/vacation_mailer.rb
- app/views/vacation_mailer/notify_vacation_cancelled.html.erb
- app/views/vacation_mailer/notify_vacation_cancelled.text.erb
- config/locales/pt-BR/views.yml
- spec/controllers/vacations_controller_spec.rb
- spec/mailers/vacation_mailer_spec.rb
Closes: #307 
- Sends an email when the user cancels a vacation to people with HR and commercial roles. It also sends as CC to HR-MAIL, added here #305.
> Feature: Send email for canceled vacations

- app/models/user.rb
Closes: #311 
It removes the city requirement for the user. If there is a user without a city, it won't be a problem anymore and won't raise `Cidade é obrigatório(a)` again. This change won't be permanent thought
> FIx: City validation constraint

- app/models/vacation.rb
Now the user can require a vacation, as long as the vacation itself has 10 days minimum. Less than 10 days, an error is raised.
the error messages still need to be adjusted. Later on, a new pr will be opened contemplating this.
> Fix: minimum days for vacation

- app/views/vacations/_form.html.erb
- It disables the autocomplete from the date-picker to make it easier for the user to choose a date
Before:
After:
> Fix: disable autocomplete from date picker

- app/views/layouts/application.html.erb
- app/views/layouts/dashboard.html.erb
- app/views/layouts/home.html.erb
- app/views/layouts/redesign.html.erb
Fixes #334 
Due to a missing `/` when a user try to access any page, the server interprets the favicon path as a relative path to the current URL and throws a missing template error
> Fixing missing png template error

- app/models/ability.rb
- app/models/vacation.rb
- spec/features/admin/allocation_chart_spec.rb
- spec/models/ability_spec.rb
Closes #332 
- It allows a user to cancel an approved vacation before 7 days it started
> Cancel an approved vacation request

- app/admin/user.rb
- app/mailers/notification_mailer.rb
- config/locales/pt-BR/models.yml
- config/locales/pt-BR/pt-BR.yml
- spec/mailers/notification_mailer_spec.rb
Adds link on the User's admin show page that allows to resend the user's registration email.
> feat: allow admin to resend the user reg email through admin

- app/assets/javascripts/active_admin/allocation_chart.js
Fixes #373 
The previous code inside `app/assets/javascripts/active_admin/allocation_chart.js` was defining a rule for `name` column to be sorted based on `hiddenTime` column. This fix removes the rule to allow `name` column to sort user names correctly.
> Fix: allocation chart sorting by user name

- app/admin/talk.rb
- app/admin/user.rb
- app/decorators/talk_decorator.rb
- config/locales/pt-BR/models.yml
- config/locales/pt-BR/pt-BR.yml
- spec/decorators/talk_decorator_spec.rb
- spec/factories/talks.rb
- spec/features/admin/talks_spec.rb
- spec/features/admin/users_spec.rb
- Adds a table in the presenting experience panel to list users talks 
- Also adds feature tests for admin/talks
Closes #407
> feat: list user talks on experience tab

- app/jobs/alert_fill_contribution_description_job.rb
- app/mailers/notification_mailer.rb
- app/services/github/contributions/create.rb
- app/views/notification_mailer/notify_fill_contribution_description.html.erb
- config/locales/pt-BR/views.yml
- spec/jobs/alert_fill_contribution_description_job_spec.rb
- spec/mailers/notification_mailer_spec.rb
- spec/services/github/contributions/create_spec.rb
This PR adds a feature to send emails to users after a contribution is approved to request a description for it.
Closes #413
> feat: notify users about contributions waiting for description

- db/seeds.rb
As holidays are associated with randomly created cities, there is a chance that the same city will be selected more than once, which generates an `ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint
"index_cities_on_regional_holidays"`.
An example can be seen in this broken run of the `test` job in the CI: https://github.com/Codeminer42/Punchclock/actions/runs/5178825930/jobs/9330828836#step:9:193
Solving this problem by checking if the city is already associated with the holiday.
> fix: error violating unique constraint when seeding holidays

- app/admin/user.rb
- app/decorators/user_decorator.rb
- app/views/new_admin/users/_details.html.erb
- spec/controllers/new_admin/users_controller_spec.rb
#388 added some changes to `user_decorator.rb` that broke the following specs:
- `spec/features/admin/users_spec.rb:121`
- `specs/spreadsheets/admins_spreadsheets_spec.rb`
- `spec/features/edit_user_spec.rb:50`
- `spec/features/dashboard_spec.rb:81`
Fixed by moving some logic from the decorator to the `new_admin/users#show` view.
#402 fixed a typo in the translations key that broke the following spec:
- `spec/features/admin/users_spec.rb:249`
All tests are passing now.
> Fix regressions in new admin pages

- docker-compose.yaml
When trying to run the project with the following command:
```
$ docker compose up
```
I would get the following error from the `app` container:
```
punchclock-app-1       | 13:44:16 rails.1  | started with pid 7
punchclock-app-1       | 13:44:16 worker.1 | started with pid 8
punchclock-app-1       | 13:44:16 css.1    | started with pid 9
punchclock-app-1       | 13:44:18 rails.1  | => Booting Puma
punchclock-app-1       | 13:44:18 rails.1  | => Rails 7.0.6 application starting in development 
punchclock-app-1       | 13:44:18 rails.1  | => Run `bin/rails server --help` for more startup options
punchclock-app-1       | 13:44:18 rails.1  | [7] Puma starting in cluster mode...
punchclock-app-1       | 13:44:18 rails.1  | [7] * Puma version: 6.3.0 (ruby 3.1.4-p223) ("Mugi No Toki Itaru") …
```
> Fix `tailwindcss:watch` failing to start in Docker container

- spec/helpers/active_admin/allocation_chart_helper_spec.rb
This PR ensures that the test setup consistently creates valid allocations when utilizing time travel. The specific test in question fails due to the factory sometimes generating an allocation with today's date. This occurs when the `rand(0..180)` call returns `0` at this line:
https://github.com/Codeminer42/Punchclock/blob/287cde734cb3cfa2522a57d20d5034e1be60585d/spec/factories/allocations.rb#L8
In the test setup, `#travel_to` is used to move to a future date, causing `Date.today` to return that future date. When combined with `rand(0..180)` returning `0`, the allocation's `start_at` is set to the future date.
The issue arises when that same future date is used as `end_at` at this line:
https://github.com/Codeminer42/Punchclock/blob/287cde734cb3cfa2522a57d20d5034e1be60585d/spec/helpers/ac …
> Fix flaky test in `allocation_chart_helper_spec.rb`

- spec/controllers/users_controller_spec.rb
- spec/support/2fa_otp_helper.rb
Previously, the spec would fail occasionally bacause of its implementation of the method `shuffle`. Due to its nature, it was possible that the code implemented would not change the original string of numbers, resulting in a failing spec.
An example of a likely scenario:
This PR aims to fix this issue, creating a support method that verifies if the shuffled string is, in fact, different from the original one.
> test: Fix flaky users controller spec

- README.md
- app/javascript/packs/utils/calendar.js
- test/javascript/packs/utils/calendar.test.js
When the month has 31 days and it starts on Saturday, its 31st day doesn't appears in the current month
And its 31st day appears disabled in the next month because it is not the current month.
This PR fix this edge case, activating the day in the next month.
> Fix calendar disabled day

- spec/helpers/active_admin/users_helper_spec.rb
The factory for Skills can occasionally return a title containing apostrophes in it, which would cause the spec validating the content_tag to fail. This PR establishes a non-volatile name for skill titles.
```
1) ActiveAdmin::UsersHelper#skills_tags returns the tags for all user's skills
Failure/Error: expect(subject).to eq("<span class=\"status_tag yes\">#{user_skills[0].skill.title}</span> <span class=\"status_tag no\">#{user_skills[1].skill.title}</span>")
expected: "<span class=\"status_tag yes\">NetLogo</span> <span class=\"status_tag no\">App Inventor for Android's visual block language</span>"
got: "<span class=\"status_tag yes\">NetLogo</span> <span class=\"status_tag no\">App Inventor for Android&#39;s visual block language</span>"
(compared using ==)
```
> test: Name skills in `users_helper_spec` to avoid encoding inconsistencies

- app/assets/javascripts/new_admin/navbar.js
Our current node version doesn't support the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) syntax. Thus, we need to manually check the element presence.
> refactor: Replace unsupported optional chaining in navBar.js

- Gemfile.lock
Fixes:
`Tailwindcss::Commands::ExecutableNotFoundException: Cannot find the tailwindcss executable for arm64-darwin in /Users/thiago/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.29/exe
`
and similar errors in arm64-powered machines.
For the security test to pass, https://github.com/Codeminer42/Punchclock/pull/529 needs to be merged.
> feat: Include arm64 platform in Gemfile.lock

- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/sessions/two_factor.html.erb
Attending to the issue #452 i added a tailwind css property `cursor-pointer` on clickable buttons and checkboxes from devise sessions, passwords and confirmations pages.
The original issue was describing Sign In and 2FA only but while i was navigating through the views i thought that it would be a good idea to adjust the same problem on other pages too.
Sign In page now:
2FA page now:
Resend password confirmation page before:
Now: 
Change password page before:
Now: 
Resend reset password instructions page before:
Now:
> improvement: add cursor pointer for devise pages

- app/assets/stylesheets/active_admin.scss
- app/views/admin/revenue_forecast/_forecasts_table.html.arb
As described on issue #542, the table on Revenue Forecasts page can become harder to read as the number of row increases, due to how much info's available at it. It would be interesting if we had a highlight on current cell's column and row when hovering over them.
To make the highlight work i used a technique that consists of creating two big pseudo-elements with the desired background color every time we hover on that cell with the mouse, being that one's for the column highlight and the other's for the row. To stop those elements to overflow the forecast's table height and width `overflow: hidden` property does the trick . For more details over that trick (credits for Talysson Oliveira) see [this link](https://css-tricks.com/simple-css-row-column-highlighting/).
Due to css hover …
> improvement: add highlight for forecasts table 

- app/admin/dashboard.rb
- app/admin/user.rb
- app/controllers/new_admin/users_controller.rb
- app/decorators/user_decorator.rb
- app/models/user.rb
- app/spreadsheets/users_spreadsheet.rb
- app/views/evaluations/index.html.erb
- app/views/new_admin/allocation_charts/_allocations.html.erb
- app/views/new_admin/users/_details.html.erb
- app/views/new_admin/users/_form.html.erb
- db/migrate/20231005131111_remove_level_from_users.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/new_admin/allocation_charts_controller_spec.rb
- spec/decorators/user_decorator_spec.rb
- spec/factories/users.rb
- spec/features/admin/dashboard_spec.rb
- spec/features/admin/users_spec.rb
- spec/features/evaluations/index.html.erb_spec.rb
- spec/models/user_spec.rb
- spec/spreadsheets/users_spreadsheet_spec.rb
This PR removes the level attribute from user. Since there is frontend level and backend level, this attribute is no longer necessary. 
Issue #537 
Main changes in the UI:
> Remove level attribute from user

- app/services/user_resume_doc.rb
This PR solves issue #545, (line was not breaking properly when adding user professional experiences to docx resume), by splitting the job description in paragraphs and adding one paragraph at a time.
> Breaking lines when adding job description with multiple paragraphs

- app/views/contributions/index.html.erb
- config/locales/pt-BR/views.yml
Closes #546 
add description column to contributions list so a user can see which PRs needs description.
Co-authored: @jonathanrib3
> feat: add description column

- app/jobs/alert_fill_contribution_description_job.rb
- app/mailers/notification_mailer.rb
- app/models/contribution.rb
- app/views/notification_mailer/notify_fill_contribution_description.html.erb
- config/locales/pt-BR/views.yml
- spec/jobs/alert_fill_contribution_description_job_spec.rb
- spec/mailers/notification_mailer_spec.rb
- spec/models/contribution_spec.rb
This PR changed the e-mail referring to PRs without description to include the links to Punchclock, instead of not specifying any of the required PRs.
Fixes #535
> fix: Add links of contributions to e-mail description

- app/controllers/contributions_controller.rb
- spec/controllers/contributions_controller_spec.rb
This PR solves issue #549, which is to show all of the users pull requests instead of just the approved ones.
> Showing all of the users prs

- app/javascript/packs/reducers/calendarReducer.js
Closes #541
- sets dashboard's sheets to an empty map if it fails to create them.
> Inaccurate Future Punch Display in Calendar UI Despite Alert Notification

- app/admin/allocations.rb
- app/models/allocation.rb
- spec/features/admin/allocations_spec.rb
- spec/models/allocation_spec.rb
Closes #576 - Adjustments on ActiveAdmin Allocations' index page
To make the hourly rates sorting work i decided to sort allocations through their value as cents - `hourly_rate_cents` and used ActiveAdmin's `sortable` property on the table structure. 
To make the hourly rates currencies filter work i added a scope that gets all available currencies from allocations table without any duplicates in ascending order, being that they're rendered through an ActiveAdmin `filter` as a select. 
A demo of how things are working right now:
> feat: add hourly rates sorts and filters on /admin/contributions

- app/admin/user.rb
- app/decorators/user_decorator.rb
- spec/features/admin/users_spec.rb
**Closes issue**  #577 - Add hourly rate column to allocations table
To solve this, I simply added on admin User's code base a column named `hourly rate`. The values in that column are going to be rendered using Allocation's Decorator, which already has a function that formats the hourly rate with their right currency symbol and amount.
Here's the result:
> feat: add hourly rates to allocations table on /admin/users page

- app/controllers/application_controller.rb
- app/controllers/professional_experiences_controller.rb
- app/views/professional_experiences/_form.html.erb
- app/views/professional_experiences/index.html.erb
- app/views/professional_experiences/new.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/locales/pt-BR/views.yml
- spec/controllers/new_admin/revenue_forecast_controller_spec.rb
- spec/features/new_admin/revenue_forecast_spec.rb
- spec/requests/professional_experiences_spec.rb
This PR completes issue #567, which was to implement the create method of the professional experiences in the user interface (outside of the admin interface). 
> Implementing professional experience create

- app/controllers/talks_controller.rb
- app/views/talks/_table.html.erb
- app/views/talks/index.html.erb
- config/locales/pt-BR/views.yml
- config/routes.rb
- spec/features/index_talks_spec.rb
- spec/requests/talks_controller_spec.rb
###Problem
**Closes Issue** #571 - Tasks index page
###Solution
To add the index page i created a controller to Talk model and created the view. The page's styled is based on /contributions page so it follows the same structure, but with pagination and without the 'go to top page' button at the bottom of the page.
This feature has feature tests too on /spec/feaetures/index_talks_spec.rb
_When the current user doesn't have saved talks_
_When the current user does have saved talks_
> feat: talks index page

- app/controllers/talks_controller.rb
- app/views/talks/new.html.erb
- app/views/talks/show.html.erb
- spec/requests/talks_controller_spec.rb
This PR completes issue #575, which was to implement the delete method for talks. 
> Implementing delete for talks

- app/views/application/_sidebar.html.erb
Closes https://github.com/Codeminer42/Punchclock/issues/651
This PR fixes the data-attribute `icon` present in sidebar's heroicons.
> fix: Uncaught TypeError in sub_menu.js
