Codeminer42/Punchclock

- app/admin/project.rb
- config/locales/pt-BR/pt-BR.yml
Fixes #21
- Add new entry to translation file
- Use `I18n.t` to display text
> Add translation to title of the pane in projects creation page

- app/admin/contributions.rb
- config/locales/pt-BR/pt-BR.yml
> Remove Reload Contributions action item

- app/views/punches/index.html.erb
- app/views/refills/_navigation.html.erb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
> Removes punch button and adds dropdown options on menu

- config/application.rb
- config/environments/test.rb
> set default time zone

- app/admin/contributions.rb
- app/queries/company_users_collection_query.rb
- spec/queries/company_users_collection_query_spec.rb
> Corrects user select collection

- lib/tasks/github.rake
Rebase with master and reorganized commits from PR https://github.com/Codeminer42/Punchclock/pull/73
> Oauth token moved from query to header#23

- app/admin/allocations.rb
- spec/features/admin/allocations_spec.rb
Related to #67 
Created conditional that permits inactive projects to be listed, but only on edit page.
https://user-images.githubusercontent.com/36737050/153637379-738d098c-2b0b-49c4-8427-074785fdfe8c.mp4
> List inactive projects on edit page

- spec/features/dashboard_spec.rb
Removed skips from dashboard tests
All tests were successful, and i couldn't find any false positives using pry.
> Remove dashboard_spec skips

- spec/features/new_punch_spec.rb
fix: Changed let when creating new user to create new logged in user instead.
> Fix test for new punch with office holiday

- .github/workflows/ruby.yml
- .tool-versions
- package.json
- yarn.lock
Fixes #108
- Set the correct version of NodeJS
- Updates the package `@rails/webpacker` to fix the problem with node-sass.
> Fix docker setup

- Gemfile.lock
- app/admin/evaluations.rb
- spec/features/admin/evaluations_spec.rb
Fixes: https://github.com/Codeminer42/Punchclock/issues/118
Fixing some issues related to the filters and adding the tests
Now, the select shows the translated name instead of the code value and the filter works.
And, adding tests for all filters to ensure that all will work.
Fix the English label level to show the translated value too.
> Fix evaluations type of questionnarie filter

- app/admin/allocations.rb
- app/queries/allocations_and_unalocated_users_query.rb
- spec/queries/allocations_and_unalocated_users_query_spec.rb
Closes #135 
New returned table example:
> Fixing AllocationsAndUnalocatedUsersQuery and table sorting

- app/admin/allocations.rb
> Fix allocation edit fields not loading

- app/controllers/dashboard_controller.rb
- app/javascript/packs/reducers/calendarReducer.js
- spec/features/dashboard_spec.rb
When trying to save punches in the future, the dashboard now alerts with correct error messages.
Tests were implemented.
[Gravação de tela de 02-08-2022 15:40:17.webm](https://user-images.githubusercontent.com/36737050/182449661-6cc6d4dc-13b2-432d-a12f-e67953323784.webm)
> Alert error message on save click

- .rubocop.yml
- Gemfile
- Gemfile.lock
- config/initializers/rswag_api.rb
- config/initializers/rswag_ui.rb
- config/routes.rb
- spec/requests/api/v1/companies_spec.rb
- spec/requests/api/v1/punches_spec.rb
- spec/requests/api/v1/token_spec.rb
- spec/swagger_helper.rb
- swagger/v1/swagger.yaml
This PR adds swagger documentation for API controllers.
Closes #103
> Documentation using OpenAPI/Swagger for the API

- app/assets/stylesheets/base/_navigation.scss
Removes rule for legacy browser already handled by autoprefixer
> Removes autoprefixer warning

- config/environments/development.rb
Setting the `default_url_options` on the mailer config
> Fixing bug with mailer

- app/admin/allocation_chart.rb
- app/models/ability_admin.rb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
- spec/features/admin/allocation_chart_spec.rb
Adds page as specified in #151
> Adds allocation chart page

- app/admin/allocation_chart.rb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
- spec/features/admin/allocation_chart_spec.rb
> Adds columns level and specialty to allocation chart table

- app/admin/allocation_chart.rb
- app/assets/stylesheets/active_admin.scss
- app/helpers/active_admin/allocation_chart_helper.rb
- spec/features/admin/allocation_chart_spec.rb
- spec/helpers/active_admin/allocation_chart_helper_spec.rb
> Highlight allocation chart rows based on the end date

- app/admin/allocation_chart.rb
- app/assets/stylesheets/active_admin.scss
* Change columns position
* Increase last column width
> Updates Allocation Chart page

- app/javascript/packs/reducers/calendarReducer.js
- app/javascript/packs/utils/calendar.js
- app/views/dashboard/index.html.erb
- package.json
- spec/features/dashboard_spec.rb
- test/javascript/packs/utils/calendar.test.js
> Show one month at a time in multiple punches calendar 

- app/admin/allocation_chart.rb
- config/locales/en.yml
- config/locales/pt-BR/pt-BR.yml
- spec/features/admin/allocation_chart_spec.rb
> Parse end_at date format

- app/admin/user.rb
- app/spreadsheets/admins_spreadsheet.rb
- config/locales/pt-BR/models.yml
- db/migrate/20220901190314_remove_user_hour_cost_column.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/users.rb
- spec/spreadsheets/admins_spreadsheet_spec.rb
Closes #181 
Remaining mentions
> Remove user's hour cost column

- app/admin/allocations.rb
- app/queries/users_by_company_query.rb
- spec/features/admin/allocations_spec.rb
- spec/queries/users_by_company_query_spec.rb
Closes #180
User allocated:
New allocation with that user:
All allocations:
Error message if new allocation has overlapped dates
> list active users to new allocation form

- app/admin/project.rb
- app/forms/allocate_users_form.rb
- app/views/admin/projects/_allocate_users.html.erb
- spec/features/admin/projects_spec.rb
Closes #174 
New project's details page
> Add dropdown list to projects datails page

- app/admin/allocation_chart.rb
- app/assets/stylesheets/active_admin.scss
- spec/features/admin/allocation_chart_spec.rb
https://github.com/Codeminer42/Punchclock/issues/179
> Adds link to allocation in column "Alocado até" in allocation chart

- app/models/allocation.rb
- app/queries/allocations_and_unalocated_users_query.rb
- config/locales/pt-BR/pt-BR.yml
- spec/models/allocation_spec.rb
- spec/queries/allocations_and_unalocated_users_query_spec.rb
Closes #187 
Allocation page:
Allocation chart:
> Allocation bug

- app/admin/allocation_chart.rb
- app/assets/javascripts/active_admin.js
- app/assets/javascripts/active_admin/allocation_chart.js
- app/assets/stylesheets/active_admin.scss
- package.json
- yarn.lock
Closes #195 
New allocation chart page
> Add datatables to allocation chart

- app/assets/javascripts/active_admin/allocation_chart.js
Remove order filter from allocations chart
> Remove: order filter from allocations chart

- app/admin/allocation_chart.rb
- app/assets/javascripts/active_admin.js
- app/assets/javascripts/active_admin/allocation_chart.js
Closes #200
Date order filter
[Gravação de tela de 08-09-2022 14:53:49.webm](https://user-images.githubusercontent.com/92229784/189196210-402be4e7-19b3-44d8-81d7-192017ecc706.webm)
> Add date order filter

- app/admin/user.rb
- app/models/user.rb
- config/locales/miners/miner.en.yml
- config/locales/miners/miner.pt-BR.yml
- config/locales/pt-BR/models.yml
- db/migrate/20220912140326_add_contract_company_country.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/users.rb
- spec/features/admin/users_spec.rb
- spec/models/user_spec.rb
> Add contract_company_country to user

- app/admin/mentoring.rb
- app/models/ability_admin.rb
- app/queries/mentoring_query.rb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
- spec/features/admin/mentoring_spec.rb
- spec/queries/mentoring_query_spec.rb
closes #203 
Mentoring screen:
> Mentoring screen

- app/models/user.rb
- spec/models/user_spec.rb
This PRs removes validation presence from user's contract_company_country
> Remove contract_company_country validation

- app/queries/mentoring_query.rb
- app/views/admin/mentoring/_offices_mentoring.html.erb
- db/seeds.rb
- spec/queries/mentoring_query_spec.rb
> Fix mentoring screen

- app/views/layouts/application.html.erb
- app/views/layouts/dashboard.html.erb
- config/initializers/assets.rb
- package.json
- yarn.lock
Webpacker and webpacker are breaking compatibility so will be addressed later
> Fix security issues

- app/admin/project.rb
- app/models/project.rb
- app/models/project_contact_information.rb
- app/views/admin/projects/_project_contact_informations.html.erb
- config/locales/en/en.yml
- config/locales/pt-BR/models.yml
- config/locales/pt-BR/pt-BR.yml
- db/migrate/20220927205438_create_project_contact_informations.rb
- db/schema.rb
- spec/factories/project_contact_informations.rb
- spec/features/admin/projects_spec.rb
- spec/models/project_contact_information_spec.rb
- spec/models/project_spec.rb
> Contact Information by Project

- Dockerfile
- README.md
- config/environments/development.rb
- docker-compose.yaml
> The docker container is not allowing to use the nodejs

- .github/workflows/ruby.yml
- db/seeds.rb
> The seeds file is not working

- app/models/vacation.rb
- db/migrate/20221011125254_create_vacations.rb
- db/schema.rb
- spec/factories/vacations.rb
- spec/models/vacation_spec.rb
> Add Vacation model

- app/admin/user.rb
- app/spreadsheets/users_spreadsheet.rb
- config/locales/pt-BR/pt-BR.yml
- spec/spreadsheets/users_spreadsheet_spec.rb
> Reimplement users spreadsheet with caxlsx gem

- Gemfile
- Gemfile.lock
- app/admin/contributions.rb
- app/spreadsheets/contributions_spreadsheet.rb
- spec/spreadsheets/allocations_spreadsheet_spec.rb
- spec/spreadsheets/contributions_spreadsheet_spec.rb
- spec/support/spreadsheet_helpers.rb
> Reimplement contributions spreadsheet

- app/admin/evaluations.rb
- app/spreadsheets/evaluations_spreadsheet.rb
- spec/spreadsheets/evaluations_spreadsheet_spec.rb
> Reimplement Offices Spreadsheet

- app/admin/office.rb
- app/spreadsheets/offices_spreadsheet.rb
- spec/spreadsheets/offices_spreadsheet_spec.rb
> Update export xlsx gem on offices_spreadsheet

- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/shared/_links.html.erb
- config/application.rb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
- spec/features/forgot_password_spec.rb
**Forgot your password:**
**Change your password:**
**Resend confirmation instructions:**
> Redesign Forgot your password,  Change your password and Resend confirmation instructions screens with TailwindCSS

- app/admin/project.rb
- app/spreadsheets/projects_spreadsheet.rb
- spec/spreadsheets/projects_spreadsheet_spec.rb
> Reimplement Projects Spreadsheet

- app/admin/questionnaires.rb
- app/spreadsheets/questionnaires_spreadsheet.rb
- spec/spreadsheets/questionnaires_spreadsheet_spec.rb
> Reimplement questionaries report with caxlsx gem

- app/admin/punch.rb
- app/spreadsheets/punches_spreadsheet.rb
- spec/spreadsheets/punches_spreadsheet_spec.rb
> Reimplement punches report with caxlsx gem

- app/admin/regional_holiday.rb
- app/spreadsheets/regional_holidays_spreadsheet.rb
- spec/spreadsheets/regional_holidays_spreadsheet_spec.rb
> Reimplement regional holiday report with caxlsx gem

- app/controllers/vacations_controller.rb
- app/models/user.rb
- app/models/vacation.rb
- app/views/refills/_navigation.html.erb
- app/views/vacations/_form.html.erb
- app/views/vacations/index.html.erb
- app/views/vacations/new.html.erb
- config/locales/en/en.yml
- config/locales/en/responders.yml
- config/locales/miners/miner.en.yml
- config/locales/miners/miner.pt-BR.yml
- config/locales/pt-BR/models.yml
- config/locales/pt-BR/pt-BR.yml
- config/locales/pt-BR/responders.yml
- config/routes.rb
- spec/controllers/vacations_controller_spec.rb
- spec/factories/vacations.rb
- spec/models/vacation_spec.rb
Closes: #275 
For a "normal" user, create pages to see, request or cancel a vacation.
The user should be able to see all your own vacations requests
The normal user cannot cancel a not pending vacation
The form will have only the start date and end date.
The end date cannot be before the start date.
The start and the end date cannot be in the past.
The end date cannot be on the same day as the start date
> Feature: Create pages for vacations in the punch normal user side

- app/mailers/application_mailer.rb
- app/mailers/vacation_mailer.rb
- app/views/vacation_mailer/notify_vacation_request.html.erb
- app/views/vacation_mailer/notify_vacation_request.text.erb
- config/locales/pt-BR/views.yml
- spec/mailers/vacation_mailer_spec.rb
Ths PR closes #284
Sending an email to admin users when a user requests a vacation including the following data:
- User name
- Start date
- End date
- Number of vacation days
> Send email when requesting vacation

- .env.test
- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
- app/admin/exchange_rates.rb
- app/models/ability_admin.rb
- app/models/exchange_rate.rb
- app/services/revenue_forecast_service.rb
- config/initializers/money.rb
- config/locales/pt-BR/models.yml
- db/migrate/20221125185846_create_exchange_rates.rb
- db/schema.rb
- spec/factories/exchange_rates.rb
- spec/features/admin/exchange_rates_spec.rb
- spec/models/exchange_rate_spec.rb
- spec/services/revenue_forecast_service_spec.rb
This PR's objective is to change how the allocations' hourly rates are converted from US dollars to Brazilian Reais. Before this change, we were using a gem to provide the exchange rate, but we can't guarantee that the value provided by this source is reliable. Because of that, we decided to create our own database of rates and use it to do the calculations
> Revenue forecast improvements

- app/admin/vacation.rb
- app/controllers/application_controller.rb
- spec/features/admin/application_spec.rb
What does this PR do?
- It redirects to the previous page after signing in when a user tries to access an URL that need must be authenticated
> Feature: redirect to previous url after login

- .env.development.local
- .env.test.local
The *.local files was in the repo, making confusion in the github workflow.
> Fix CI - Remove *.local files

- app/models/vacation.rb
- lib/tasks/vacations.rake
> Rake task to cancel not approved vacations

- app/admin/mentoring.rb
- app/admin/user.rb
- app/models/user.rb
- app/queries/mentoring_query.rb
- app/views/admin/mentoring/_offices_mentoring.html.erb
- config/locales/pt-BR/models.yml
- spec/models/user_spec.rb
- spec/queries/mentoring_query_spec.rb
> feat: add mentees row in user's admin page

- app/mailers/vacation_mailer.rb
- app/models/user.rb
- app/models/vacation.rb
- app/views/vacation_mailer/notify_pending_vacations.html.erb
- config/locales/pt-BR/views.yml
- lib/tasks/vacations.rake
- spec/controllers/vacations_controller_spec.rb
- spec/mailers/vacation_mailer_spec.rb
- spec/models/user_spec.rb
- spec/models/vacation_spec.rb
> Feat: E-mail remembering the hr/commercial team of the pending vacations

- README.md
> update README.md to add yarn as a dependency

- app/models/vacation.rb
- config/locales/pt-BR/models.yml
- spec/features/vacation_spec.rb
> Fix the date locale when the vacation create has failed

- app/admin/regional_holiday.rb
- app/assets/javascripts/active_admin.js
- app/assets/javascripts/active_admin/regional_holiday.js
- app/helpers/active_admin/regional_holidays_helper.rb
- app/models/city.rb
- app/models/regional_holiday.rb
- app/models/user.rb
- app/views/vacations/_form.html.erb
- config/locales/pt-BR/models.yml
- db/migrate/20230419142222_create_cities_regional_holidays.rb
- db/schema.rb
- lib/tasks/migrate_offices_holidays.rake
- spec/factories/cities.rb
- spec/models/city_spec.rb
- spec/models/regional_holiday_spec.rb
- spec/models/user_spec.rb
WIP: #346 
After data is normalized we can remove offices_regional_holidays relationship.
> feat: regional holidays using cities

- README.md
> fix: remove unnecessary setup steps

- app/controllers/new_admin/punches_controller.rb
- app/models/punch.rb
- app/views/new_admin/allocations/_allocated_user_punches.html.erb
- app/views/new_admin/punches/show.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/controllers/new_admin/punches_controller_spec.rb
> feat: page for punch info

- app/controllers/new_admin/allocations_controller.rb
- app/views/layouts/new_admin.html.erb
- app/views/new_admin/allocations/_form.html.erb
- app/views/new_admin/allocations/edit.html.erb
- app/views/new_admin/allocations/show.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/controllers/new_admin/allocations_controller_spec.rb
> feature: new admin edit allocation page

- app/admin/user.rb
- config/locales/pt-BR/pt-BR.yml
This PR solves the issue #406 
- Add new experience tab to the user admin page
> Feat: add new experience tab

- app/admin/contributions.rb
- app/models/contribution.rb
- config/locales/pt-BR/active_admin.yml
- config/locales/pt-BR/models.yml
- db/migrate/20230512124753_add_columns_to_contribution.rb
- db/schema.rb
- spec/features/admin/contributions_spec.rb
- spec/models/contribution_spec.rb
> Feat: Add tracking tab in contributions admin list

- app/admin/vacation.rb
- app/models/vacation.rb
- config/locales/pt-BR/active_admin.yml
- spec/models/vacation_spec.rb
> feat: add finished scope to vacation

- app/controllers/new_admin/users_controller.rb
- app/decorators/user_decorator.rb
- app/views/new_admin/allocation_chart/_allocations.html.erb
- app/views/new_admin/users/_details.html.erb
- app/views/new_admin/users/show.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/controllers/new_admin/users_controller_spec.rb
> feature: new admin page for user info

- app/admin/user.rb
- app/decorators/contribution_decorator.rb
- app/decorators/repository_decorator.rb
- config/locales/pt-BR/models.yml
- spec/decorators/repository_decorator_spec.rb
- spec/factories/contributions.rb
- spec/features/admin/users_spec.rb
Adds open source history to Experience tab
Closes #408.
> feat: Add open source history to Experience tab

- app/controllers/new_admin/users_controller.rb
- app/views/new_admin/users/_english_evaluations.html.erb
- app/views/new_admin/users/show.html.erb
- config/locales/pt-BR/models.yml
- config/locales/pt-BR/pt-BR.yml
- spec/controllers/new_admin/users_controller_spec.rb
- spec/features/new_admin/user_english_evaluation_spec.rb
- spec/features/new_admin/users_spec.rb
> feat: new admin user english evaluation page

- app/admin/education_experiences.rb
- app/admin/user.rb
- app/models/ability_admin.rb
- app/models/education_experience.rb
- app/models/user.rb
- config/locales/pt-BR/models.yml
- db/migrate/20230524004351_create_education_experiences.rb
- db/schema.rb
- spec/admin/education_experience_spec.rb
- spec/factories/education_experiences.rb
- spec/features/admin/education_experiences_spec.rb
- spec/models/education_experience_spec.rb
Adds ability for admins to include users education experience.
Closes #412
> feat: Add users education experience

- app/assets/javascripts/active_admin/allocation_chart.js
Reverts Codeminer42/Punchclock#378
> Revert "Fix: allocation chart sorting by user name"

- app/admin/professional_experiences.rb
- app/models/ability_admin.rb
- app/models/professional_experience.rb
- app/models/user.rb
- config/locales/pt-BR/models.yml
- db/migrate/20230601185451_create_professional_experiences.rb
- db/schema.rb
- spec/admin/professional_experience.rb
- spec/factories/professional_experiences.rb
- spec/features/admin/professional_experience.rb
- spec/models/professional_experience_spec.rb
Adds ability for admins to include users professional experience.
Closes #410
> feat: add users professional experience

- app/admin/user.rb
- spec/factories/contributions.rb
- spec/features/admin/users_spec.rb
>  feat: list only approved contributions in the experience tab

- app/admin/professional_experiences.rb
- app/admin/user.rb
- app/decorators/education_experience_decorator.rb
- app/decorators/professional_experience_decorator.rb
ThisPr closes #409 
- it lists the  user professional experience
> [FEAT-409] List user professional experience

- spec/support/capybara.rb
The old setup was causing an ArgumentError
> Update Capybara setup

- app/admin/repositories.rb
- app/queries/repository_query.rb
- db/migrate/20230714130703_add_highlight_to_repositories.rb
- db/schema.rb
> Highlight an OSS

- .gitignore
- app/controllers/new_admin/regional_holidays_controller.rb
- app/models/city.rb
- app/models/regional_holiday.rb
- app/views/new_admin/regional_holidays/_regional_holiday_details.html.erb
- app/views/new_admin/regional_holidays/_regional_holidays_filters.html.erb
- app/views/new_admin/regional_holidays/_regional_holidays_table.html.erb
- app/views/new_admin/regional_holidays/show.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/controllers/new_admin/regional_holidays_controller_spec.rb
- spec/features/new_admin/regional_holidays_spec.rb
- spec/models/city_spec.rb
- spec/models/regional_holiday_spec.rb
Based on: https://github.com/Codeminer42/Punchclock/pull/489
Closes https://github.com/Codeminer42/Punchclock/issues/492
> feat: New admin regional holidays show page

- .gitignore
- app/controllers/new_admin/regional_holidays_controller.rb
- app/views/new_admin/regional_holidays/_form.html.erb
- app/views/new_admin/regional_holidays/index.html.erb
- app/views/new_admin/regional_holidays/new.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/controllers/new_admin/regional_holidays_controller_spec.rb
- spec/features/new_admin/regional_holidays_spec.rb
Closes https://github.com/Codeminer42/Punchclock/issues/493
> feat: New admin regional holidays creation page

- app/controllers/new_admin/evaluations_controller.rb
- app/decorators/evaluation_decorator.rb
- app/views/new_admin/evaluations/index.html.erb
- spec/controllers/new_admin/evaluations_controller_spec.rb
- spec/features/new_admin/evaluations_spec.rb
First part of https://github.com/Codeminer42/Punchclock/issues/495
> feat: Paginate New Admin Evaluations

- spec/mailers/vacation_mailer_spec.rb
Closes https://github.com/Codeminer42/Punchclock/issues/505
> test: Fix flaky vacation mailer spec

- app/controllers/concerns/new_admin/pagination.rb
- app/controllers/new_admin/allocation_charts_controller.rb
- app/controllers/new_admin/evaluations_controller.rb
- app/decorators/allocation_decorator.rb
- app/views/new_admin/allocation_charts/_allocations.html.erb
- app/views/new_admin/allocation_charts/index.html.erb
- spec/controllers/new_admin/allocation_charts_controller_spec.rb
- spec/controllers/new_admin/concerns/pagination_spec.rb
- spec/features/new_admin/allocation_charts_spec.rb
- spec/support/controller_test_class_for_pagination.rb
Part 2 of https://github.com/Codeminer42/Punchclock/issues/495
> feat: Paginate new admin allocation charts

- .gitignore
- app/assets/javascripts/new_admin_application.js
- app/controllers/new_admin/regional_holidays_controller.rb
- app/models/regional_holiday.rb
- app/views/new_admin/regional_holidays/_regional_holidays_table.html.erb
- app/views/new_admin/regional_holidays/edit.html.erb
- app/views/new_admin/regional_holidays/show.html.erb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/controllers/new_admin/regional_holidays_controller_spec.rb
- spec/features/new_admin/regional_holidays_spec.rb
Closes https://github.com/Codeminer42/Punchclock/issues/501 and https://github.com/Codeminer42/Punchclock/issues/502
> feat: Destroy action for regional holidays

- app/admin/allocations.rb
> fix: Date formats in Allocations form

- app/admin/user.rb
- app/models/professional_experience.rb
- app/services/user_resume_doc.rb
- spec/models/professional_experience_spec.rb
- spec/services/user_resume_doc_spec.rb
https://github.com/Codeminer42/Punchclock/pull/532 needed
> refactor: Order professional experiences by start date in user admin

- app/controllers/api/v1/allocations_controller.rb
- app/javascript/packs/api.js
- app/javascript/packs/components/Calendar.js
- app/javascript/packs/components/Form.js
- app/javascript/packs/reducers/calendarReducer.js
- config/routes.rb
- spec/controllers/api/v1/allocations_controller_spec.rb
Closes #491.
- Add the auto-focus in the search field of the project after click on the combobox.
- Add auto-select based on the current allocation when open the dashboard.
> improvement: Auto focus on project allocation field and auto-select based on the current allocation

- Gemfile
- Gemfile.lock
Reverts Codeminer42/Punchclock#532
> Revert "chore(deps): bump sidekiq from 6.5.9 to 7.1.3"

- Gemfile
- Gemfile.lock
Upgrades sidekiq to 6.5.12 patch
> chore(deps): upgrade sidekiq from 6.5.9 to 6.5.12

- app/controllers/professional_experiences_controller.rb
- app/models/professional_experience.rb
- app/views/professional_experiences/index.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/models/professional_experience_spec.rb
- spec/requests/professional_experiences_spec.rb
This PR solves issue #565, which was to create an index page for professional experiences in the user interface (outside of the admin interface). 
> Professional experiences index

- app/controllers/new_admin/questionnaires_controller.rb
- app/models/ability.rb
- app/models/questionnaire.rb
- app/queries/new_admin/questionnaires_query.rb
- app/views/application/_sidebar.html.erb
- app/views/new_admin/questionnaires/_questionnaires_filter.html.erb
- app/views/new_admin/questionnaires/_questionnaires_table.html.erb
- app/views/new_admin/questionnaires/index.html.erb
- config/locales/en/en.yml
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/models/questionnaire_spec.rb
- spec/queries/new_admin/questionnaires_query_spec.rb
- spec/requests/new_admin/questionnaires_controller_spec.rb
This PR Completes the index page of new_admin questionnaires, described in issue #551 
> Index questionnaires new admin

- app/controllers/new_admin/allocation_charts_controller.rb
- app/controllers/new_admin/allocations_controller.rb
- app/controllers/new_admin/evaluations_controller.rb
- app/controllers/new_admin/mentorings_controller.rb
- app/controllers/new_admin/projects/allocate_users_controller.rb
- app/controllers/new_admin/projects_controller.rb
- app/controllers/new_admin/punches_controller.rb
- app/controllers/new_admin/questionnaires_controller.rb
- app/controllers/new_admin/regional_holidays_controller.rb
- app/controllers/new_admin/revenue_forecast_controller.rb
- app/controllers/new_admin/users_controller.rb
- app/controllers/new_admin/vacations_controller.rb
- app/controllers/new_admin_controller.rb
- app/models/ability_admin.rb
- app/views/new_admin/projects/_projects_table.html.erb
- app/views/new_admin/projects/show.html.erb
- spec/controllers/new_admin/evaluations_controller_spec.rb
- spec/controllers/new_admin/mentorings_controller_spec.rb
- spec/controllers/new_admin/projects_controller_spec.rb
- spec/controllers/new_admin/regional_holidays_controller_spec.rb
- spec/controllers/new_admin/revenue_forecast_controller_spec.rb
- spec/features/new_admin/projects_spec.rb
- spec/features/new_admin/revenue_forecast_spec.rb
- spec/requests/new_admin/questionnaires_controller_spec.rb
> Refactor new admin

- app/views/new_admin/questionnaires/_questionnaires_table.html.erb
Removing conflict resolution lines.
> fixing questionnaires new admin views

- app/admin/user.rb
- app/controllers/new_admin/users_controller.rb
- app/models/user.rb
- app/queries/new_admin/users_query.rb
- app/views/application/_sidebar.html.erb
- app/views/new_admin/users/_users_filter.html.erb
- app/views/new_admin/users/_users_table.html.erb
- app/views/new_admin/users/index.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/models/user_spec.rb
- spec/queries/new_admin/users_query_spec.rb
- spec/requests/new_admin/users_controller_spec.rb
> Feat: Index page for users in new admin

- spec/models/repository_spec.rb
This PR fixes an intermitent test in the respository model spec.
> fixing intermitent test in repository model

- app/controllers/new_admin/notes_controller.rb
- app/views/new_admin/notes/_form.html.erb
- app/views/new_admin/notes/_notes_table.html.erb
- app/views/new_admin/notes/edit.html.erb
- app/views/new_admin/notes/show.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/requests/new_admin/notes_controller_spec.rb
This PR completes issue #628 , which was to implement the edit/update methods for the notes in the new admin interface. 
> implementing edit and update methods

- app/controllers/new_admin/repositories_controller.rb
- app/views/new_admin/repositories/_repositories_table.html.erb
- app/views/new_admin/repositories/edit.html.erb
- app/views/new_admin/repositories/show.html.erb
- config/locales/pt-BR/pt-BR.yml
- config/routes.rb
- spec/features/new_admin/repositories_spec.rb
- spec/requests/new_admin/repositories_controller_spec.rb
> Feat: Edit repository new admin

- app/spreadsheets/allocations_spreadsheet.rb
- config/locales/pt-BR/pt-BR.yml
- spec/spreadsheets/allocations_spreadsheet_spec.rb
This PR changes the data returned in the allocations spreadsheet to accomodate new needs that have risen.
> Export allocations with new data to accomodate needs
